// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44411' | (string & {});
};

export type ScheduleItemModel = {
    key: string;
    name: string;
    action: string;
    culture?: string | null;
    scheduledAt: string;
    status: string;
};

export type ScheduleCountsModel = {
    today: number;
    next7Days: number;
    next30Days: number;
    overdue: number;
};

export type ScheduleItemsResponse = {
    items: Array<ScheduleItemModel>;
    counts: ScheduleCountsModel;
};

export type ScheduleRange = 'Today' | 'Next7Days' | 'Next30Days' | 'Overdue';

export type GetScheduleItemsData = {
    body?: never;
    path?: never;
    query?: {
        range?: ScheduleRange;
    };
    url: '/umbraco/dynamicdave-schedule/api/v1/items';
};

export type GetScheduleItemsErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetScheduleItemsResponses = {
    /**
     * OK
     */
    200: ScheduleItemsResponse;
};

export type GetScheduleItemsResponse = GetScheduleItemsResponses[keyof GetScheduleItemsResponses];
